version: '3.8'

env_file:
  - .env

services:
  awp_nestjs_be_api_dev:
    container_name: awp_nestjs_be_api_dev
    image: awp_nestjs_be_api_dev:1.0.0
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - awp_nestjs_be_mongodb 
    volumes:
      - ./:/usr/src/app
    command: npm run start
    restart: unless-stopped

  awp_nestjs_be_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  awp_nestjs_be_mongo_express:
    container_name: awp_nestjs_be_mongo_express
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME} # 2 biến này dùng làm basic
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD} # auth khi truy cập mongo_express
      ME_CONFIG_MONGODB_URL: ${DATABASE_URI}?authSource=admin # Đây là thông tin kết nối tới database
    ports:
      - 8002:8081
    depends_on:
      - awp_nestjs_be_mongodb
    restart: unless-stopped

networks:
  default:
    driver: bridge
