on:
  push:
    branches: [develop]
    paths: ['src', 'package.json', 'yarn.lock']

  workflow_dispatch: 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        if: github.ref == 'refs/heads/develop'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"