name: Deploy to Server

on:
  push:
    branches:
      - develop
      
  workflow_dispatch: 

env:
  CONTAINER_NAME: awp_nestjs_be

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Decode .env.production
        uses: akiojin/decode-base64-github-action@v0.1.0
        with:
          base64: ${{ secrets.ENV_PROD_FILE }}
          output-path: .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: production
          push: true
          tags: dqvinh20/awp_nestjs_be:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Stop and remove old container
            docker stop ${{ env.CONTAINER_NAME }} || true && docker rm ${{ env.CONTAINER_NAME }} || true

            # Remove dangling images
            sudo docker image prune

            # Remove image
            docker image rmi dqvinh20/awp_nestjs_be:latest || true

            # Start new container
            docker run -d \
              --restart always \
              --name ${{ env.CONTAINER_NAME }} \
              --add-host host.docker.internal:host-gateway \
              -p 5050:3000 \
              dqvinh20/awp_nestjs_be:latest
